[package]
name = "virust-founder"
version = "0.1.0"
edition = "2024"

[dependencies]
bio = "3.0.0"
clap = { version = "4.5.54", features = ["derive"] }
reqwest = { version = "0.13.1", features = ["multipart", "blocking"] }
thiserror = "2.0.17"
